services:
  db:
    image: mysql:8
    container_name: "${APP_NAME}-db"
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT_INTERNAL}:${DB_PORT_EXTERNAL}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - marketflow_api_network_docker

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: "${APP_NAME}-app"
    working_dir: /app
    volumes:
      - ./:/app
    command: sh /app/docker/php/init.sh
    depends_on:
      - db
      - redis
    networks:
      - marketflow_api_network_docker

  nginx:
    image: nginx:alpine
    container_name: "${APP_NAME}-nginx"
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - marketflow_api_network_docker

  redis:
    image: redis:alpine
    container_name: "${APP_NAME}-redist"
    ports:
      - "${REDIS_PORT_INTERNAL}:${REDIS_PORT_EXTERNAL}"
    networks:
      - marketflow_api_network_docker

volumes:
  db_data:

networks:
  marketflow_api_network_docker:
    driver: bridge
